services:
  - type: web
    name: citylight-sindhi-samaj-mbms
    env: python
    region: singapore
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask init-db && flask seed-demo && gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: citylight-sindhi-samaj-db
          property: connectionString

databases:
  - name: citylight-sindhi-samaj-db
    plan: starter
    region: singapore
